language: c

compiler:
  - gcc

env:
  - TEST_FILE=`realpath testfile.txt`

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov
      - doxygen
      - help2man

script:
  - cppcheck --error-exitcode=1 --enable=warning,performance,information,style static_library/*.c
  - cppcheck --error-exitcode=1 --enable=warning,performance,information,style dynamic_library/*.c
  - cppcheck --error-exitcode=1 --enable=warning,performance,information,style include/*.h
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd static_test
  - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./test_static
  - lcov --directory . --capture --output-file coverage.info
  - cd -
  - cd dynamic_test
  - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./test_dynamic
  - lcov --directory . --capture --output-file coverage.info